first-subChart:
  name: nginx
  deployment:
    containers:
      nginx:
        name: nginx
        image:
          repository: nginx
          tag: latest
        ports:
        - name: nginx
          port: 80
        envFromSecret:
        - name: example
        - name: example-crt
        - name: example-key
second-subChart:
  name: redis
  deployment:
    containers:
      redis:
        name: redis
        image:
          repository: redis
          tag: latest
        ports:
        - name: redis
          port: 6379
        envFromSecret:
        - name: example

secrets:
  example:
    data:
      EXAMPLE_SECRET: bar
      EXMAPLE_TLS: |-
        -----BEGIN CERTIFICATE-----
        MIICqDCCAZACCQCsmHF586CU4TANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAtm
        b28uYmFyLmNvbTAeFw0yMTA3MDIwMzE1NTNaFw0yMjA3MDIwMzE1NTNaMBYxFDAS
        BgNVBAMMC2Zvby5iYXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
        AQEAqc2AIhnZU5vMw755cCirooUjMkuOhp+ZmYB3D1qHiT6/mppIygGGYy6c7kWL
        kjZmyPnXDRUg9W+7sPOVGYhFGOiU2V7dNrNZTME7/wn5/PdQBE5j2cGCQXf/hHpi
        JedmUpCPR9cL4ixi6AbgojPCBsdthKue68BX9FmTCeNBH+DVlOEZbHnBm5NC3ork
        YFisoR/2CyGPdxoNF6aZfETaHcH+K+4DZFiVz4KF8r/JCmQRvO4bAtJTeLLYCrgU
        CCTHlDPSBUF0pdWdN7IRYAU67IAkpgMkPADYHStbyskHVqNa9uT+3GfS9ryo5gnW
        QzPVk6q6o/XCksBgGLZ02PvTWwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBXepVf
        ci3dmruHCWTy+Au1i2+/4VveN8hqyH93fUrxZ5ejiPPgCp6oCit5iihibz1JHw14
        UrAREDROKdWTKoC9/F58brKEb0U7GbN5h1Cf4sdme+M8DzFAopXcG8ZXfnAEmMbK
        mdRxedL4Ez+MJyfgD+Cucac5JAMc8L/QrQkc1rCH2naGGSrO99YqNRnsgzKFg2zy
        v0WJ7tC9IkqTJdca+kw0PsQvMcpuodTDiIsSV69JoRWK8PCJxUaxFuwPRuH6KXsI
        80I4d9TAmKQfr8R1hjAX7vLvgwuHRnjHhPZdCRoM3irjnoVpQ0nmuW7UiSCA0b2y
        xcPaL4GCgUl+8TiK
        -----END CERTIFICATE-----
secretsFromfile:
  example-crt:
    key: EXAMPLE_CRT
    file: "tls/tls.crt"
  example-key:
    key: EXAMPLE_KEY
    file: "tls/tls.key"