apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.name }}
  {{- with .Values.labels }}
  labels:
    {{ toYaml . }}
  {{- end }}
spec:
  eventBusName: {{ .Values.name }}
  {{- with .Values.eventsensor.config }}
  replicas: {{ .replicas | default 1 }}
  {{- end }}
  service:
    ports:
      - port: {{ .Values.eventsource.config.servicePort | default 12051 }}
        targetPort: 12051
  {{- with .Values.eventsource.source -}}
  {{if eq (include "helper.containType" (list . "webhook" )) "yes" }}
  webhook:
    {{- range $index, $element := . }}
    {{- if eq $element.type "webhook" }}
    {{ template "source_webhook" $element }}
    {{- end }}
    {{- end }}
  {{- end -}}
  {{ end }}