apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.name }}
  {{- with .Values.labels }}
  labels:
    {{ toYaml . }}
  {{- end }}
spec:
  eventBusName: {{ .Values.name }}
  service:
    ports:
      - port: {{ .Values.eventsource.config.servicePort | default 12051 }}
        targetPort: 12051
  webhook:
    {{- range $index, $element := .Values.eventsource.source }}
    {{- if eq $element.type "webhook" }}
    {{ template "source_webhook" $element }}
    {{- end }}
    {{- end }}