{{- if .Values.enableArgoWorkflowsDefaultRole }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-{{ .Release.Namespace }}-argo-workflows-admin
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["events", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["eventsources", "sensors", "workflows", "workfloweventbindings", "workflowtemplates", "cronworkflows"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-{{ .Release.Namespace }}-argo-workflows-admin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-argo-workflows-admin-service-account
roleRef:
  kind: Role
  name: role-{{ .Release.Namespace }}-argo-workflows-admin
  apiGroup: rbac.authorization.k8s.io
{{- end}}