{{- if .Values.customRole }}

{{- $projectName := .Release.Name }}
{{- $namespace := .Release.Namespace }}

{{- range .Values.customRole }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-{{ $projectName }}-{{ .name }}
  namespace: {{ $namespace }}
rules:
{{- range .rules }}
  - apiGroups: 
    {{- range .apiGroups }}
    - {{ . | quote }}
    {{- end}}
    resources: 
    {{- range .resources }}
    - {{ . | quote }}
    {{- end}}
    verbs: 
    {{- range .verbs }}
    - {{ . | quote }}
    {{- end}}
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-{{ $projectName }}-{{ .name }}
  namespace: {{ $namespace }}
subjects:
  - kind: Group
    name: group-{{ $projectName }}-{{ .name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-{{ $projectName }}-{{ .name }}
  apiGroup: rbac.authorization.k8s.io
---

{{- end}}
{{- end}}