{{ range .Values.workers }}
{{ $resourceName := (ternary .name .queue (not (empty .name))) }}
{{ $worker := merge . $.Values.global (dict "resourceName" $resourceName) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}-{{ $resourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.name }}-{{ $resourceName }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ $.Values.name }}-{{ $resourceName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}-{{ $resourceName }}
    spec:
      containers:
      - {{ template "deployment.container" $worker }}
      restartPolicy: Always
      {{- if $.Values.serviceaccount}}
      serviceAccountName: {{ $.Values.name }}-pod-service-account
      {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      terminationGracePeriodSeconds: 61
---
{{- end }}