{{ range .Values.workers }}
{{- if .hpav2 }}
  {{- if (default .standAlone false ) }}
    {{ fail "Don't create HPA at standalone mode." }}
  {{- end }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  minReplicas: {{ .hpav2.minReplicas }}
  maxReplicas: {{ .hpav2.maxReplicas }}
  metrics:
  {{- range .hpav2.Resource }}
  - type: Resource
    resource:
      name: {{ .name }}
      target:
        {{- if .percent}}
        type: Utilization
        averageUtilization: {{ .percent }}
        {{- else if .value}}
        type: AverageValue
        averageValue: {{ .value }}
        {{- end }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.name }}-{{ .name }}
---      
{{- end}}
{{- end}}