apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      backoffLimit: {{ .Values.job.retries }}
      activeDeadlineSeconds: {{ .Values.job.timeout }}
      restartPolicy: Never
      containers:
        -
          name: app
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- if .Values.command }}
          command: {{- toYaml .Values.command | nindent 14 }}
          {{- end }}
          {{- if hasKey .Values "resources" }}
          resources: {{ toYaml .Values.resources | nindent 14 }}
          {{- end }}
          env:
            - name: POD_NAME
              value: {{ .Values.name }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $name := .Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}
                  key: {{ $key | quote }}
            {{- end }}
