{{- /* If kind = "CronWorkflow", RoleBinding for argo workflow will be created */}}
{{- if and (.Values.kind ) (eq .Values.kind "CronWorkflow") }}
# Following RoleBinding needed for argo workflow 3.5
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wf-role-binding-{{ .Values.name }}-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-role-{{ .Values.name }}-executor
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceaccount }}
  name: {{ .Values.serviceaccount.name | default (printf "%s-pod-service-account" .Values.name) }}
  {{- else }}
  name: {{ .Values.name }}-pod-service-account
  {{- end }}
{{- end }}