apiVersion: apps/v1
kind: Deployment
metadata:
  name: andytest
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if not (or .Values.hpa .Values.hpav2) }}
  replicas: {{ .Values.replicaCount }}
  {{- end}}
  strategy:
  {{- if hasKey .Values.deployment "strategy" }}
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  {{- else}}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if hasKey .Values "tolerations" }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end}}
      {{- if hasKey .Values "nodeSelector" }}
      nodeSelector:
        {{ .Values.nodeSelector.labelName }}: {{ .Values.nodeSelector.labelValue }} 
      {{- end}}
      {{- if hasKey .Values.deployment "affinity" }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end}}
      {{- if hasKey .Values "securityContextForPod" }}
      securityContext: 
        {{ toYaml .Values.securityContextForPod | nindent 8 }}        
      {{- end}}
      containers:
{{- if hasKey .Values.deployment "containers" }}
  {{- range .Values.deployment.containers }}
      - {{ template "deployment.container" . }}
  {{- end}}
{{- else}}
      - {{ template "deployment.container_legacy" .Values }}
{{- end}}
      {{- if hasKey .Values.deployment  "volumes" }}
      volumes:
        {{- range $key, $vol := $.Values.deployment.volumes }}
        - name: {{ $vol.name }}
          {{- if hasKey $vol "secret" }}
          secret:
            {{- toYaml $vol.secret | nindent 12 }}
          {{- end }}
          {{- if hasKey $vol "configMap" }}
          configMap:
            name: {{ $vol.name }}
          {{- end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.serviceaccount}}
      serviceAccountName: {{.Values.name }}-pod-service-account
      {{- end }}
      {{- if .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.deployment.dnsConfig | nindent 8 }}
      {{- else }}
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds | default "30" }}
