{{- if .Values.ingress }}
{{ include "resource_tag_checker" . }}
{{- if hasKey .Values "EnableMutilpleIngress" }}
{{ template "ingress.ingress_multiple" . }}
{{- else }}
{{ template "ingress.ingress_single" . }}
{{- end}}
{{- end}}