{{- if .Values.roleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.roleBinding.roleRef.kind | default "Role" }}
  name: {{ .Values.roleBinding.roleRef.name }}
subjects:
{{- range .Values.roleBinding.subjects }}
- kind: {{ .kind }}
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}