# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test/pipeline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.ANDY_PAT || github.token}} 
      # Runs a single command using the runners shell
      - name: Download helm binary
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

          # git config --global user.name 'andychuang'
          # git config --global user.email 'andy.chuang@shoplineapp.com'
      - name: Sync master branch to github-pages branch
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'ci@users.noreply.github.com'
          git fetch
          git checkout github-pages
          ls -al simple/
          git branch --show-current
          git pull origin test/pipeline --allow-unrelated-histories -X theirs

      - name: Package helm chart file and create index.yaml
        run: |
          helm version
          helm package simple -d simple
          helm package fluentd-cloudwatch -d fluentd-cloudwatch
          helm package cronjob -d cronjob
          helm repo index . --url https://shoplineapp.github.io/helm-charts
          ls -al simple/
          cat index.yaml

      - name: Update github pages
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'ci@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shoplineapp/helm-charts
          git status
          git add */*.tgz index.yaml
          git commit -m 'update chart version'
          git push origin github-pages